from enum import Enum


class ErrorCode(str, Enum):
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    REFUND_NOT_ALLOWED = "REFUND_NOT_ALLOWED"
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
